### ISSUE TITLE
Syntax error caused by the 3 dots(...), please help ...

### ISSUE THREAD

**Issue by Hussein-Shaito** [VirgilSecurity/virgil-e3kit-firebase-func#15]
```

C:\Users\Cheaito\Desktop\Androd git\virgil-e3kit-firebase-func\functions\node_modules\chokidar\index.js:904
  const options = {type: EV_ALL, alwaysStat: true, lstat: true, ...opts};
                                                                ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Cheaito\Desktop\Androd git\virgil-e3kit-firebase-func\functions\node_modules\firebase-tools\lib\emulator\functionsEmulator.js:21:18)

    at ChildProcess.exithandler (child_process.js:252:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'firebase functions:config:set virgil.app_key="APP_KEY" virgil.app_id="APP_ID" virgil.app_key_id="APP_KEY_ID"' }

```

Node version 8
Windows 10
npm 6.11.3

@xlwknx

**Comment by Hussein-Shaito** [comment]
Thank you 
I solve it
@xlwknx
